// src/db/init.js
// Run once to create all tables: `node src/db/init.js`

const db = require('./connection');

const schema = `
  -- ──────────────────────────────────────────────
  -- USERS
  -- role: 'patient' | 'clinician'
  -- ──────────────────────────────────────────────
  CREATE TABLE IF NOT EXISTS users (
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    name       TEXT    NOT NULL,
    email      TEXT    NOT NULL UNIQUE,
    role       TEXT    NOT NULL DEFAULT 'patient',
    created_at TEXT    NOT NULL DEFAULT (datetime('now'))
  );

  -- ──────────────────────────────────────────────
  -- SESSIONS
  -- One rehabilitation session per row.
  -- ended_at is NULL while the session is active.
  -- ──────────────────────────────────────────────
  CREATE TABLE IF NOT EXISTS sessions (
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    started_at TEXT    NOT NULL DEFAULT (datetime('now')),
    ended_at   TEXT
  );

  -- ──────────────────────────────────────────────
  -- MEASUREMENTS
  -- One row per sensor reading inside a session.
  -- joint_angles stored as JSON string.
  -- is_correct comes from V1 AI inference.
  -- ──────────────────────────────────────────────
  CREATE TABLE IF NOT EXISTS measurements (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id   INTEGER NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    timestamp    TEXT    NOT NULL DEFAULT (datetime('now')),
    joint_angles TEXT    NOT NULL,
    is_correct   INTEGER NOT NULL DEFAULT 0
  );

  -- ──────────────────────────────────────────────
  -- RECOMMENDATIONS
  -- Generated by the recommendation engine from
  -- historical session data.
  -- status: 'pending' | 'accepted' | 'rejected'
  -- ──────────────────────────────────────────────
  CREATE TABLE IF NOT EXISTS recommendations (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id  INTEGER NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    movement    TEXT    NOT NULL,
    status      TEXT    NOT NULL DEFAULT 'pending',
    confidence  REAL    NOT NULL DEFAULT 0.0,
    created_at  TEXT    NOT NULL DEFAULT (datetime('now'))
  );

  -- Indexes for common queries
  CREATE INDEX IF NOT EXISTS idx_sessions_user   ON sessions(user_id);
  CREATE INDEX IF NOT EXISTS idx_meas_session    ON measurements(session_id);
  CREATE INDEX IF NOT EXISTS idx_recs_session    ON recommendations(session_id);
`;

db.exec(schema);
console.log('✅  Database initialised at data/v2.db');
